### ISSUE TITLE
Unable to find a specification for `MHPinterestLayout`

### ISSUE THREAD

**Issue by Gaganpreetkaur** [michaelhenry/MHPinterestLayout#2]
pod install
Analyzing dependencies
[!] Unable to find a specification for `MHPinterestLayout`

**Comment by michaelhenry** [comment]
Just need to update your pod repo

please try this:
```
pod install --repo-update
```

Cheers 👍

**Comment by Gaganpreetkaur** [comment]
Now Im getting 
[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

**Comment by michaelhenry** [comment]
then please try to execute that `pod repo update` instead. thanks
```
pod repo update --verbose
```
