### ISSUE TITLE
Different sections

### ISSUE THREAD

**Issue by kronik** [michaelhenry/MHPinterestLayout#3]
Hi! Is there an option to display full-width cells in between this layout?

**Comment by kronik** [comment]
For example, I have 10 sections and every first cell in section has a full width

**Comment by michaelhenry** [comment]
these are the public vars that you can use for your requirements. 

```
    public var headerHeight:CGFloat = 200
    public var footerHeight:CGFloat = 0
    public var horizontalCellSpacing:CGFloat = 10.0
    public var verticalCellSpacing:CGFloat = 10.0
```

cheers 🥂

**Comment by michaelhenry** [comment]
so in example setupCollectionView()
```
 func setupCollectionView() {
        
        layout.configure {
            $0.delegate = self
            $0.headerHeight = 150
            $0.columns = UIApplication.shared.statusBarOrientation == .portrait ? 2 : 3
 
 $0.horizontalCellSpacing:CGFloat = 0.0
 $0.verticalCellSpacing:CGFloat = 0.0

        }
        
        collectionView
            .configure {
                $0.setCollectionViewLayout(layout, animated: false)
                $0.delegate = self
                $0.dataSource = self
                $0.register(ItemCollectionViewCell.self)
                $0.registerHeader(HeaderReusableView.self)
                $0.backgroundColor = UIColor.white
        }
    }
```

**Comment by kronik** [comment]
yeah.. saw that... But it's not a footer or header, it's just another cell.

**Comment by michaelhenry** [comment]
@kronik sorry for late reply, I have been busy on my work. Currently that configuration is not available on this library, however, that can be achieve by making `cellContentWidth` as part of the delegate of `MHPinterestLayoutDelegate` (https://github.com/michaelhenry/MHPinterestLayout/blob/master/MHPinterestLayout/Classes/MHPinterestLayout.swift) per indexPath.
